name: Check formulae

on:
  push:
    branches: [main]
  
  pull_request:
    branches: [main]

jobs:
  run-tests:
    name: ${{ matrix.formula }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        formula: ['kosmorro']

    steps:
      - uses: actions/checkout@v4

      - name: Add tap
        run: |
          brew tap kosmorro/tap
          rm -rf /opt/homebrew/Library/Taps/kosmorro/homebrew-tap
          cp -r . /opt/homebrew/Library/Taps/kosmorro/homebrew-tap

      - name: Install `${{ matrix.formula }}` formula
        run: |
          brew install ${{ matrix.formula }}

      - name: Run tests
        run: |
          brew test ${{ matrix.formula }}

      - name: Run audit
        run: |
          brew audit --strict --formula ${{ matrix.formula }}
